name: Question
description: Request a question
title: "[Question]: "
labels: ["question"]
body:
  - type: textarea
    id: question
    attributes:
      label: Your question
      description: Try to ask your question as clearly as possible
    validations:
      required: true