name: Node.js CI

on: [push, pull_request]

jobs:
  test:
    name: Test the build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
    
    steps:
    - name: Actions checkout 
      uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Package-lock generation
      run: cd encoder && npm i --package-lock-only
    - name: Initiate build client
      run: cd encoder && npm ci
    - name: Run build script
      run: cd encoder && npm run-script build
    - name: Set action secrets
      run: echo ${{ secrets.VRCHAT_USERNAME }}.${{ secrets.VRCHAT_PASSWORD }}.${{ secrets.VRCHAT_AVATAR_ID }} > encoder/tests/.env
    - name: Run test script
      run: cd encoder && npm run-script test
